definitions:
  service.LoginPasswordRequest:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  service.SetRoleCreateRequest:
    properties:
      is_admin:
        type: integer
      menu_identities:
        description: 被授权的菜单列表
        items:
          type: string
        type: array
      name:
        type: string
      sort:
        type: integer
    type: object
  service.SetRoleUpdateAdminRequest:
    properties:
      identity:
        description: 角色唯一标识
        type: string
      is_admin:
        description: 是否是超管【0-否 1-是】
        type: integer
    type: object
  service.SetRoleUpdateRequest:
    properties:
      identity:
        description: 角色唯一标识
        type: string
      is_admin:
        type: integer
      menu_identities:
        description: 被授权的菜单列表
        items:
          type: string
        type: array
      name:
        type: string
      sort:
        type: integer
    type: object
  service.SetUserAddRequest:
    properties:
      password:
        type: string
      phone:
        type: string
      role_identity:
        type: string
      username:
        type: string
    type: object
  service.SetUserUpdateRequest:
    properties:
      identity:
        type: string
      password:
        type: string
      phone:
        type: string
      role_identity:
        type: string
      username:
        type: string
    type: object
  service.UserPasswordChangeRequest:
    properties:
      new_password:
        description: 新密码
        type: string
      old_password:
        description: 旧密码
        type: string
    type: object
info:
  contact: {}
paths:
  /functions:
    get:
      parameters:
      - description: AccessToken
        in: header
        name: AccessToken
        required: true
        type: string
      responses:
        "200":
          description: '{"code":"200","data":""}'
          schema:
            type: string
      summary: 获取功能列表
      tags:
      - 登录信息认证-方法
  /login/password:
    post:
      parameters:
      - description: 登录信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.LoginPasswordRequest'
      responses:
        "200":
          description: '{"code":"200","data":""}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 公共方法
  /menus:
    get:
      parameters:
      - description: AccessToken
        in: header
        name: AccessToken
        required: true
        type: string
      responses:
        "200":
          description: '{"code":"200","data":""}'
          schema:
            type: string
      summary: 获取菜单列表
      tags:
      - 登录信息认证-方法
  /set/func/list:
    get:
      parameters:
      - description: AccessToken
        in: header
        name: AccessToken
        required: true
        type: string
      responses:
        "200":
          description: '{"code":"200","data":""}'
          schema:
            type: string
      summary: 获取功能列表
      tags:
      - 鉴权接口-方法
  /set/menu/list:
    get:
      parameters:
      - description: AccessToken
        in: header
        name: AccessToken
        required: true
        type: string
      responses:
        "200":
          description: '{"code":"200","data":""}'
          schema:
            type: string
      summary: 获取菜单列表
      tags:
      - 鉴权接口-方法
  /set/role/create:
    post:
      parameters:
      - description: AccessToken
        in: header
        name: AccessToken
        required: true
        type: string
      - description: 角色信息
        in: body
        name: password
        required: true
        schema:
          $ref: '#/definitions/service.SetRoleCreateRequest'
      responses:
        "200":
          description: '{"code":"200","data":""}'
          schema:
            type: string
      summary: 角色创建
      tags:
      - 鉴权接口-方法
  /set/role/delete:
    delete:
      parameters:
      - description: AccessToken
        in: header
        name: AccessToken
        required: true
        type: string
      - description: identity
        in: query
        name: identity
        required: true
        type: string
      responses:
        "200":
          description: '{"code":"200","data":""}'
          schema:
            type: string
      summary: 角色删除
      tags:
      - 鉴权接口-方法
  /set/role/detail:
    get:
      parameters:
      - description: AccessToken
        in: header
        name: AccessToken
        required: true
        type: string
      - description: identity
        in: query
        name: identity
        required: true
        type: string
      responses:
        "200":
          description: '{"code":"200","data":""}'
          schema:
            type: string
      summary: 角色详情
      tags:
      - 鉴权接口-方法
  /set/role/list:
    get:
      parameters:
      - description: AccessToken
        in: header
        name: AccessToken
        required: true
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: keyword
        in: query
        name: keyword
        type: string
      responses:
        "200":
          description: '{"code":"200","data":""}'
          schema:
            type: string
      summary: 获取角色列表
      tags:
      - 鉴权接口-方法
  /set/role/update:
    put:
      parameters:
      - description: AccessToken
        in: header
        name: AccessToken
        required: true
        type: string
      - description: 所修改用户信息
        in: body
        name: UserUpdate
        required: true
        schema:
          $ref: '#/definitions/service.SetRoleUpdateRequest'
      responses:
        "200":
          description: '{"code":"200","data":""}'
          schema:
            type: string
      summary: 角色修改
      tags:
      - 鉴权接口-方法
  /set/role/update/admin:
    put:
      parameters:
      - description: AccessToken
        in: header
        name: AccessToken
        required: true
        type: string
      - description: 管理员设置
        in: body
        name: password
        required: true
        schema:
          $ref: '#/definitions/service.SetRoleUpdateAdminRequest'
      responses:
        "200":
          description: '{"code":"200","data":""}'
          schema:
            type: string
      summary: 修改角色的管理员身份
      tags:
      - 鉴权接口-方法
  /set/user/add:
    post:
      parameters:
      - description: AccessToken
        in: header
        name: AccessToken
        required: true
        type: string
      - description: 新增管理员信息
        in: body
        name: UserAddRequest
        required: true
        schema:
          $ref: '#/definitions/service.SetUserAddRequest'
      responses:
        "200":
          description: '{"code":"200","data":""}'
          schema:
            type: string
      summary: 管理员创建
      tags:
      - 鉴权接口-方法
  /set/user/delete:
    delete:
      parameters:
      - description: AccessToken
        in: header
        name: AccessToken
        required: true
        type: string
      - description: identity
        in: query
        name: identity
        required: true
        type: string
      responses:
        "200":
          description: '{"code":"200","data":""}'
          schema:
            type: string
      summary: 管理员删除
      tags:
      - 鉴权接口-方法
  /set/user/list:
    get:
      parameters:
      - description: AccessToken
        in: header
        name: AccessToken
        required: true
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: keyword
        in: query
        name: keyword
        type: string
      responses:
        "200":
          description: '{"code":"200","data":""}'
          schema:
            type: string
      summary: 管理员列表
      tags:
      - 鉴权接口-方法
  /set/user/update:
    put:
      parameters:
      - description: AccessToken
        in: header
        name: AccessToken
        required: true
        type: string
      - description: 新增管理员信息
        in: body
        name: UserAddRequest
        required: true
        schema:
          $ref: '#/definitions/service.SetUserUpdateRequest'
      responses:
        "200":
          description: '{"code":"200","data":""}'
          schema:
            type: string
      summary: 管理员修改
      tags:
      - 鉴权接口-方法
  /user/info:
    get:
      parameters:
      - description: AccessToken
        in: header
        name: AccessToken
        required: true
        type: string
      responses:
        "200":
          description: '{"code":"200","data":""}'
          schema:
            type: string
      summary: 获取用户信息
      tags:
      - 登录信息认证-方法
  /user/password/change:
    put:
      parameters:
      - description: AccessToken
        in: header
        name: AccessToken
        required: true
        type: string
      - description: 新旧密码
        in: body
        name: password
        required: true
        schema:
          $ref: '#/definitions/service.UserPasswordChangeRequest'
      responses:
        "200":
          description: '{"code":"200","data":""}'
          schema:
            type: string
      summary: 修改密码
      tags:
      - 登录信息认证-方法
swagger: "2.0"
